version: '3'

services:
  quilc:
    image: rigetti/quilc
    command: -S
    expose:
      - "5555"
    ports:
    - '5555:5555'
    networks:
      - test

  qvm:
    image: rigetti/qvm
    command: -S
    expose:
      - "5000"
    ports:
    - '5000:5000'
    networks:
      - test

networks:
  test:
    driver: bridge

