#!/usr/bin/env bash

curl -sSL https://install.python-poetry.org | python3 -
. $HOME/.poetry/env
poetry --version
poetry config virtualenvs.in-project true
poetry run python -m ensurepip --upgrade
poetry install -vv
