name: 'Commit Message Check'
on:
  push:
    branches: [ master, rc ]
  pull_request:
    branches: [ master, rc ]
  workflow_dispatch:

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Breaking|Update|Fix|New|Upgrade|No code|Release v):'
          flags: ''
          error: 'Your commit message should start with a valid semantic release verb as defined in package.json. You may also prepend "No code:" to indicate the commit does not contain changes to the released code.'
          checkAllCommitMessages: true
          excludeDescription: true
          excludeTitle: true
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
